import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results';
import request from '../utils/request';

export default function Home(props) {

  console.log(props)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />
        <Nav />
        <Results />
    </div>
  )
}

export async function getServersideProps(context){
  const genre = context.query.genre;

  const requests = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`).then((res) => res.json());

  return{
    props:{
      results : requests.results
    }
  }

}
